PotMaker:LoadLanguage {
	name = "de",

	traitNames =
	{
		["Restore Health"] = "Leben wiederherstellen",
		["Ravage Health"] = "Lebensverwüstung",
		["Restore Magicka"] = "Magicka wiederherstellen",
		["Ravage Magicka"] = "Magickaverwüstung",
		["Restore Stamina"] = "Ausdauer wiederherstellen",
		["Ravage Stamina"] = "Ausdauerverwüstung",
		["Increase Weapon Power"] = "Erhöht Waffenkraft",
		["Lower Weapon Power"] = "Verringert Waffenkraft",
		["Increase Spell Power"] = "Erhöht Magiekraft",
		["Lower Spell Power"] = "Verringert Magiekraft",
		["Weapon Crit"] = "Kritische Waffentreffer",
		["Lower Weapon Crit"] = "Verringert kritische Waffentreffer",
		["Spell Crit"] = "Kritische Magietreffer",
		["Lower Spell Crit"] = "Verringert kritische Zaubertreffer",
		["Increase Armor"] = "Erhöht Rüstung",
		["Lower Armor"] = "Verringert Eure physische Resistenz",
		["Increase Spell Resist"] = "Erhöht Magieresistenz",
		["Lower Spell Resist"] = "Verringert Eure Magieresistenz",
		["Unstoppable"] = "Sicherer Stand",
		["Stun"] = "Betäubung",
		["Speed"] = "Tempo",
		["Reduce Speed"] = "Reduziert Tempo",
		["Invisible"] = "Unsichtbarkeit",
		["Detection"] = "Detektion",

		["Sustained Restore Health"] = "Beständige Heilung",
		["Creeping Ravage Health"] = "Schleichende Lebensverwüstung",
		["Vitality"] = "Vitalität",
		["Vulnerability"] = "Verwundbarkeit",
		["Protection"] = "Schutz",
		["Defile"] = "Schänden",
	},
}