PotMaker:LoadLanguage {
	name = "fr",

	traitNames =
	{
		["Restore Health"] = "Rend de la Santé",
		["Ravage Health"] = "Réduit la Santé",
		["Restore Magicka"] = "Rend de la Magie",
		["Ravage Magicka"] = "Réduit la Magie",
		["Restore Stamina"] = "Rend de la Vigueur",
		["Ravage Stamina"] = "Ravage de Vigueur",
		["Increase Weapon Power"] = "Augmente la puissance de l'arme",
		["Lower Weapon Power"] = "Diminue la puissance de l'arme",
		["Increase Spell Power"] = "Augmente la puissance des sorts",
		["Lower Spell Power"] = "Diminue la puissance des sorts",
		["Weapon Crit"] = "Critique d'armes",
		["Lower Weapon Crit"] = "Diminue l'arme critique",
		["Spell Crit"] = "Critique de sorts",
		["Lower Spell Crit"] = "Diminue le sort critique",
		["Increase Armor"] = "Augmente l'armure",
		["Lower Armor"] = "Diminue la Résistance physique",
		["Increase Spell Resist"] = "Augmente la résistance aux sorts",
		["Lower Spell Resist"] = "Diminue la Résistance aux sorts",
		["Unstoppable"] = "Implacable",
		["Stun"] = "Sonne",
		["Speed"] = "Vitesse",
		["Reduce Speed"] = "Réduit la vitesse",
		["Invisible"] = "Invisible",
		["Detection"] = "De détection",

		["Sustained Restore Health"] = "Récupération de Santé prolongée",
		["Creeping Ravage Health"] = "Ravage de Santé insidieux",
		["Vitality"] = "Vitalité",
		["Vulnerability"] = "Vulnérabilité",
		["Protection"] = "Protection",
		["Defile"] = "Profanation",
	},
}