local localization_strings = {
SI_TK_NAME = "Diebesrucksack Extended",
SI_TK_LOCKED = "Fenster gesperrt",
SI_TK_UNLOCKED = "Fenster entsperrt",
SI_TK_INITIALIZE = "Initialisiert... fröhliches Stehlen!",
SI_TK_NOT_NA = "Sorry, aber Sie sind nicht auf der NA Megaserver oder Sie haben vernachlässigt, einen Betrag eingeben.",
-- Settings Panel

SI_TK_FIELDS = "Felder",
SI_TK_WELCOME_NAME = "Chat-Begrüßung",
SI_TK_WELCOME_MSG = "Chat-Nachricht bei Add-on-Initialisierung aktivieren/deaktivieren",
SI_TK_SCOUNT_NAME = " Anzahl gestohlener Gegenstände",
SI_TK_SCOUNT = "Zeigt an, wie viele gestohlene Gegenstände sich momentan im Inventar befinden (inklusive Stacks)",
SI_TK_RMCOUNT_NAME = " Anzahl gestohlener Rezepte/Handwerksmotive",
SI_TK_RMCOUNT = "Zeigt an, wie viele gestohlene Rezepte oder Handwerksmotive sich momentan im Inventar befinden",
SI_TK_LDXP_NAME = " Erfahrung Lug und Trug",
SI_TK_LDXP = "Es ist einfach schön, wenn die Zahl immer größer wird",
SI_TK_SELLS_NAME = "Zeigt übrige Hehler-Verkäufe",
SI_TK_SELLS = "Zeigt an, wie viele Hehler-Verkäufe für den Tag noch übrig sind",
SI_TK_LAUNDERS_NAME = "... zeigt auch Gegenstandswäsche",
SI_TK_LAUNDERS = "Zeigt an, wieviele Gegenstände an diesem Tag noch gewaschen werden können",
SI_TK_FRESET_NAME = "Hehler-Reset",
SI_TK_FRESET = "Zeigt Countdown bis zum Hehler-Reset",
SI_TK_BCLOCK_NAME = "Zeigt Countdown bis zum Kopfgeld-Reset",
SI_TK_BCLOCK = "(\"Dynamic Bounty\" blendet diese Anzeige aus, wenn kein Kopfgeld vorliegt)",
SI_TK_SBOUNTY_NAME = "Kopfgeld anzeigen",
SI_TK_SBOUNTY = "(\"Dynamic Bounty\" blendet diese Anzeige aus, wenn kein Kopfgeld vorliegt)",
SI_TK_SAVALUE_NAME = "Durchschnittswert anzeigen",
SI_TK_SAVALUE = "Zeigt den Stückpreis pro Gegenstand an (Wert/Anzahl)",
SI_TK_EDP_NAME = "Geschätzten Tagesgewinn anzeigen",
SI_TK_EDP = "Zeigt eine Schätzung des täglichen Gewinns an, basierend auf dem Wert der gestohlenen Gegenstände und der verbleibenden Hehler-Interaktionen",
SI_TK_SAQ_NAME = "Durchschnittsqualität anzigen",
SI_TK_SAQ = "Zeigt die durchschnittliche Gegenstandsqualität an",
SI_TK_DQG_NAME = "Qualitätsgraphen anzeigen",
SI_TK_DQG = "Zeigt die Gegenstandsqualität in Prozent als Graphen an",
SI_TK_OPTIONS_NAME= "Optionen",
SI_TK_DCJ_NAME = "Trödel ignorieren",
SI_TK_DCJ = "Wenn ein gestohlener Gegenstand als Trödel markiert ist, wird er nicht berücksichtigt",
SI_TK_SEPRAM_NAME = "Rezepte und Handwerksstile trennen",
SI_TK_SEPRAM = "gestohlene Handwerksstile oder Rezepte separat berechnen und nicht in den Gesamtwert einbeziehen.",
SI_TK_SEPGEAR_NAME = "Ausrüstung getrennt berechnen",
SI_TK_SEPGEAR = "Gestohlene Rüstung und Waffen nicht in den Gesamtwert einbeziehen",
SI_TK_DBT_NAME = "Dynamischer Kopfgeld-Timer",
SI_TK_DBT = "Kopfgeld-Timer je nach Kopfgeld automatisch zeigen/verstecken",
SI_TK_DISPLAY_NAME = "Anzeige",
SI_TK_SCALE_NAME = "Skalierung",
SI_TK_COMPACT_NAME = "Kompakte Anzeige",
SI_TK_COMPACT = "Wird die Leiste kompakter anzeigen, indem die Größe an die Zahlen angepasst wird",
SI_TK_SBG_NAME = "Hintergrund anzeigen",
SI_TK_SBG = "Der Hinterrund wird nur angezeigt, wenn diese Option ausgewählt ist.",
SI_TK_HIDE_IN_MENUS_NAME = "In Menü-Szenen ausblenden",
SI_TK_HIDE_IN_MENUS = "Wenn diese Option aktiviert ist, wird die Leiste in Menüs u.Ä. ausgeblendet",
SI_TK_ALIGN_NAME = "Ausrichtung",
SI_TK_ALIGN = "An welcher Bildschirmecke soll sich die Leiste ausrichten?",
SI_TK_SNAP_CENTER_NAME = "im Zentrum fixieren",
SI_TK_SNAP_CENTER = "Diese Option fixiert die Leiste im Zentrum des Bildschirms",
SI_TK_LOCK_NAME = "Leiste sperren",
SI_TK_LOCK = "Diese Option wird die Leiste fixieren, sodass sie nicht mehr verschoben werden kann.",
SI_TK_HIDE_METER_NAME = "Kopfeld-Anzeige verstecken",
SI_TK_HIDE_METER = "Diese Option wird die Standard-Kopfgeldanzeige ausblenden",
SI_TK_RL_UI = "Interface neu laden",
SI_TK_GOLD_VALUE_NAME = " Gold-Wert",
SI_TK_GOLD_VALUE = "Gold-Wert gestohlener Gegenstände anzeigen",
SI_TK_AUTO_LOCK_NAME = "Automatische Sperre",
SI_TK_AUTO_LOCK = "Dies wird automatisch das Fenster, wenn Sie es nach dem Verschieben zu sperren.",
SI_TK_DON_AND_FB = "Spenden und Feedback",
SI_TK_DONATE_TEXT = "Entwickeln und Testen dieses Addons kann teuer werden, all die Wohltaten, bitte spenden, um zu helfen, die Kosten zu tragen.",
SI_TK_LEDGERDEMAIN = "Lug und Trug^N",
SI_TK_TEXT_LABEL_NAME = "Textbeschriftungen",
SI_TK_TEXT_LABEL = "Schaltet die Anzeige von Textbeschriftungen um, die die angezeigten Elemente beschreiben.",
SI_TK_LAUNDERS_LEFT_LABEL = "Verkauft/Launders:",
SI_TK_SELLS_LEFT_LABEL = "Verkauft:",
SI_TK_TOTAL_VALUE_LABEL = "Gesamtwert:",
SI_TK_ITEM_COUNT_LABEL = "Stückzahl:",
SI_TK_RECIPE_COUNT_LABEL = "Rezept Anzahl:",
SI_TK_CURRENT_BOUNTY_LABEL = "Aktuelle Bounty:",
SI_TK_AVG_VALUE_LABEL = "Durchschnittswert:",
SI_TK_EST_PROFIT_LABEL = "Geschätzter Tagesertrag:",
SI_TK_AVG_QUALITY_LABEL = "Durchschnittliche Qualität:",
SI_TK_TL_WARNING = "Funktioniert am besten im Compact-Modus.",
SI_TK_RESET_TIMER = "Hehler-Reset: ",

SI_TK_DISPLAY_TT = "Anzeigeoptionen.",
SI_TK_OPTIONS_TT = "Allgemeine Optionen.",
SI_TK_FIELDS_TT = "Optionen für die Anzeige von Bildschirmelementen",
SI_TK_FILTERS_TT = "Filteroptionen, welche Elemente für die Berechnung der Summe berücksichtigt werden",
SI_TK_FILTERS_NAME = "Filter",
}

for stringId, stringValue in pairs(localization_strings) do
   ZO_CreateStringId(stringId, stringValue)
   SafeAddVersion(stringId, 1)
end
